### PR TITLE
Fix for wasm32-wasi target

### LINKED ISSUE #19: Only enable for wasm32-unknown-unknown
Rust supports 3 WASM targets:
- wasm32-unknown-emscripten
- wasm32-unknown-unknown
- wasm32-wasi

Both wasm32-wasi and wasm32-unknown-emscripten have working `Instant` types in libstd, so this crate should only enable the custom `Instant` type for wasm32-unknown-unknown.

### PR DESCRIPTION
**Pull request by coolreader18**
Fixes #19

### CODE REVIEW

**Comment by coolreader18** [comment]
The `cfg()`s are getting pretty unwieldy, should I add `cfg-if` and use that?

**Comment by sebcrozet** [comment]
Thank you for this PR!

> The cfg()s are getting pretty unwieldy, should I add cfg-if and use that?

Yeah, that's a good idea.

**Comment by MTRNord** [comment]
Hi just wondering why the PR removes `pub use std::time::Duration;` ?

**Comment by coolreader18** [comment]
Oh, oops, that would be a breaking change wouldn't it

**Comment by MTRNord** [comment]
Well at least for one of the crates I use. Not sure how many actually use that re-export. But it certainly would break peoples crates :)

**Comment by coolreader18** [comment]
@sebcrozet could you review this?

**Comment by MTRNord** [comment]
@coolreader18 thanks :) working again now

**Comment by youknowone** [comment]
I am also waiting for this

**Comment by sebcrozet** [comment]
Thanks!

**Pull request merged**
